Memberships/Memberships/Controllers/FileController.cs
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Memberships.Controllers
{
    [Authorize]
    public class FileController : Controller
    {
        // GET: File
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            var path = Server.MapPath("~/Content/Files");
            var dir = new DirectoryInfo(path);
            var files = dir.EnumerateFiles().Where(f => f.Extension != ".gitignore").Select(f => f.Name);

            return View(files);
        }

        // Sending file to the /Content/Files/ directory
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult Index(HttpPostedFileBase file)
        {
            var path = Path.Combine(Server.MapPath("~/Content/Files/"), file.FileName);
            var data = new byte[file.ContentLength];
            file.InputStream.Read(data, 0, file.ContentLength);
            using (var sw = new FileStream(path, FileMode.Create))
            {
                sw.Write(data, 0, data.Length);
            }

            return RedirectToAction("Index");
        }
    }
}

Memberships/Memberships/Views/File/Index.cshtml
@model IEnumerable<string>

@{
    ViewBag.Title = "Index"; 
}

<h2>Files</h2>
<ul>
    @foreach (var fName in Model)
    {
        var name = fName;
        var link = @Url.Content("~/Content/Files/") + name.Replace(" ", "%20");
        <li>
            <a href="@link">@name</a>
        </li>
    }
</ul>
<div>
    @using (Html.BeginForm("Index", "File", FormMethod.Post, new
    {
        enctype = "multipart/form-data"
    }))
    {
        <input type="File" name="file" id="file" value="Choose File" />
        <button type="submit">Upload</button>
    }
</div>